services:
  webShuffle: #8443
    image: animals-sequence-track-player:v10
    container_name: web_shuffle_animals_9
    volumes:
      - /smb/ssd/Animals/FULLY_PROCESSED/:/mnt/p/VOX/FULLY_PROCESSED/
      - /home/adam/.local/share/docker/volumes/self-signed/_data/:/etc/ssl/certs/java/carts/
    restart: unless-stopped
    ports:
      - 192.168.181.24:97:8443