services:
  webShuffle: #8443
    image: sequence-track-player:v10
    container_name: web_shuffle_9
    volumes:
      - /smb/ssd/feed/FULLY_PROCESSED/:/mnt/p/feed/FULLY_PROCESSED/
      - /var/lib/docker/volumes/self-signed/_data/:/etc/ssl/certs/java/carts/
    restart: unless-stopped
    ports:
      - 192.168.0.24:84:8443
    networks:
      - frontend
networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.193.0/24
          gateway: 192.168.193.1 